### ISSUE TITLE
feat: add latest support to /patches

### ISSUE THREAD

**Issue by Ushie** [revanced/revanced-api#10]
"latest":

![image](https://github.com/revanced/revanced-api/assets/79272171/b9ddd97b-26b6-4551-915a-1aa03dd022fd)

"v2.184.0":
![image](https://github.com/revanced/revanced-api/assets/79272171/eaf24c7c-dcd0-46b7-81d6-bcdd72a14df2)

This is an issue as not all clients are aware of the tags and which is the latest, such as ReVanced Website

**Comment by oSumAtrIX** [comment]
I suggest the following:

- /patches returns the latest
- /patches/latest alias of the above
- /patches/{tag} return the specific tagged version

A problem i see right now is, how would {tag} be ever known? The API does never supply a list of tags, you can not know which tags exist. This issue might be considered

**Comment by alexandreteles** [comment]
> I suggest the following:
> 
> * /patches returns the latest
> * /patches/latest alias of the above
> * /patches/{tag} return the specific tagged version
> 
> A problem i see right now is, how would {tag} be ever known? The API does never supply a list of tags, you can not know which tags exist. This issue might be considered

This oversight originated from thinking clients were too smart and would always order specific requests. For example, by checking the latest release (`GET /revanced-patches/releases/latest`) for the patches product *before* requesting the latest patches.

I do not intend to implement aliases, especially because the root namespace is reserved for the compatibility layer. So expect to see `/patches/latest` only.

**Comment by alexandreteles** [comment]
This modification was implemented, so you can now request `/patches/latest` or `/patches/latest?dev=true`. This issue will automatically close once I merge the PR.
