### ISSUE TITLE
bug: blocked by CORS policy

### ISSUE THREAD

**Issue by jairajmahadev** [ReVanced/revanced-api#191]
### Bug description

Access to fetch at 'https://api.revanced.app/v3/patches/list' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
It's not really a bug in the API. Its an environment specific config. Requesting from localhost won't work with authentication due to browser security anyways. The cors hosts are limited to revanced.app and it's subdomains. A temporary DNS change in your local hosts file could work. I'll add localhost to the cors config though

**Comment by oSumAtrIX** [comment]
Give it a shot

**Comment by jairajmahadev** [comment]
Thankyou for the quick response! I'll try the DNS change

**Comment by jairajmahadev** [comment]
> Give it a shot

Worked flawlessly. Thankyou so much
